apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app   # ✅ Namespace explicitly defined
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  namespace: demo-app   # ✅ Namespace explicitly defined
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort  # You can change this to LoadBalancer if on cloud
